[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
DeDe es un sistema de venta online creado para una empresa de venta de productos relacionados con el deporte. La aplicación respeta la privacidad de los clientes siguiendo los principios SOLID.

Por tanto, el sistema no almacenará información de los clientes, obtendrá aquella para la que los usuarios den permiso.
****

=== Requirements Overview

[role="arc42help"]
****
Los requisitos funcionales que ofrecerá nuestra aplicación serán los siguientes:

* Los usuarios podrán seleccionar y encargar productos a comprar.
* El sistema se encargará de calcular los costes de envío dependiendo de la distancia que haya entre el centro de distribución y la dirección que tenga el usuario en su pod.
* El sistema mostrará costes finales de toda la compra y cuando el usuario acepte, registrará el evento que simula la venta realizada y se procederá al envío.
* Los usuarios podrán visualizar los pedidos realizados.
****

=== Quality Goals

[role="arc42help"]
****
[options="header",cols="1,2,2"]
|===
|**Quality Goal**|**Motivación**|**Prioridad**
| _<Q1>_ | _<M1>_ | _<P1>_
| _<Q2>_ | _<M2>_ | _<P2>_
|===
****

=== Stakeholders

[role="arc42help"]

[options="header",cols="1,2,2"]
|===
|**Rol/NOMBRE**|**Expectaciones**
| _<Rol-1>_ | _<Expectación-1>_
| _<Rol-2>_ | _<Expectación-2>_
|===
