[[section-system-scope-and-context]]
== Contexto y Alcance del Sistema

=== Contexto de negocio
****
[plantuml,"Business Context",png]
----

:Cliente: as cliente

package "Navegador web" {
[DeDe-WebSite] as web
[User Pod] as pod
}


cliente .down.> web : accede
cliente -down-> pod : tiene
web .right.> pod : obtine datos
web <.left.pod : devuelve datos
----

.Cliente
El usuario o cliente es una persona interesada en acceder a nuestra página para ver y potencialmente comprar alguno de nuestros productos.

.DeDe-Website
Representa nuestro producto, la página web, donde se alojan los productos y donde los clientes pueden hacer sus pedidos.

.User Pod
Consiste en un almacén de datos descentralizado bajo la especificación Solid y cuyo propietario (el cliente) puede permitir el acceso a parte de la información para el correcto funcionamiento de nuestra página web.
****

=== Contexto técnico
****

El producto consiste en una página web comercial alojada en un servidor/nodo y que se comunica con el backend (DeDe-RestApi), que encuentra en otro nodo, mediante protocolo HTTP.
Además, para respetar la privacidad de nuestros consumidores, hacemos uso de las especificaciones Solid. Para obtener esta característica, nuestro frontend se comunica con el proveedor del Pod del usuario..

Finalmente, existe una base de datos MongoDB para el almacenamiento de datos.

[plantuml,"Technical Context",png]
----

[DeDe-WebApp] as app
[SOLID Pod Provider] as pod
[DeDe-RestApi] as api
[DeDe-MongoDB] as db

app -right- api : internet/http
pod -down- app : internet/http
api -down- db: internet/http

----
****