[[section-solution-strategy]]
== Estrategia de solución


=== Decisiones tecnológicas
****
Las tecnologías usadas en nuestra aplicación van a ser las siguientes:

* React: es una biblioteca de código abierto de JavaScript diseñada para crear interfaces de usuario y también simplifica la portabilidad de la aplicación entre plataformas. Con esta herramienta vamos a crear la interfaz de usuario de nuestra aplicación.
* GitHub: herramienta donde guardaremos el código de nuestra aplicación. 
* Solid: nuestra aplicación tiene que seguir estos principios de descentralización de la información del usuario. 
* MongoDB: es una base de datos orientada a documentos. Esto quiere decir que en lugar de guardar los datos en registros, guarda los datos en documentos. Una de las diferencias con las bases de datos relacionales, es que no necesita seguir ningún esquema. Esta clasificado como una base de datos NoSql.
* MVC: es un patrón que seguiremos en nuestra aplicación. Es un patrón arquitectónico usado para aplicaciones que necesitan una interfaz de usuario.
* Typescript: es el lenguaje que usamos en nuestra aplicación. 
* Tailwind UI: es el frameworks de CSS que vamos a utilizar en la aplicación.
* API Shippo: es una api que se usa para calcular los costes de envio. Se elije porque tiene su propia blioteca para node y permite consultar los costes de envio
    sin necesidad de validar direcciones o preocuparse de impuestos y tasas de aduanas. También dispone de un entorno de pruebas gratuito.
* Gatling: programa para realizar los test de carga.
****
=== Objetivos de calidad
****
.Privacidad

Queremos que nuestra aplicación sea un lugar seguro, así que nos centraremos en la privacidad de los usuarios y de sus datos. Debemos almacenar la menor cantidad de información del usuario, ya que esto aumenta su privacidad y reduce la posibilidad de que el usuario sea atacado.

.Usabilidad

Un objetivo de nuestra aplicación es que sea usable, es decir, que sea facil de entender y usar. La usabilidad es la disciplina que estudia la forma de diseñar aplicaciones para que los usuarios puedan interactuar con ellos de la forma más fácil, cómoda e intuitiva posible

Para conseguir este objetivo tenemos que crear nuestra aplicación realizando un diseño centrado en el usuario, es decir, nuestra aplicación esta diseñada por y para el usuario.

.Eficiencia

Necesitamos que nuestra aplicación sea eficiente, es decir, que haga lo que nosotros queremos que haga y no otra cosa. Desde el punto de vista del usuario, esto significa que cuando entre en la aplicación, se encuentre lo que el queria y no le sea dificil encontrar lo que necesitaba, ya que si no el usuario optara por abandonar la aplicación.

.Robustez del sistema

Un sistema robusto es un sistema fuerte, sin debilidades ni vacíos de seguridad. La robustez en un programa informático hace referencia a su capacidad para hacer frente a errores mientras se está ejecutando. 

Para cumplir este objetivo, tendremos que crear nuestra aplicación centrándonos en que cuando el usuario la utilice no encuentre errores, o en caso de encontrarlos, que no afecten al correcto funcionamiento de la aplicación.
****
=== Decisiones organizativas
****
* Uso de ramas: para desarrollar la documentación hemos creado un rama doc, sobre la que realizaremos los cambios individualmente y haremos un pullRequest sobre la rama dev. Finalmente, cuando la documentación este completa la pasaremos a la rama Master, que es la rama principal del proyecto.
* Issues: para organizar las distintas tareas que tenemos que realizar para continuar con nuestra aplicación.
* Discussions: usamos esta funcionalidad de gitHub para dejar constancia de deciones importantes (modelo de datos por ejemplo) y para realizar votaciones.
* Tableros del proyecto: es una manera de que todo el equipo pueda ver como van las tareas pendientes. Es decir, se puede ver que tareas aún no se han empezado, cuáles están en proceso y cuáles ya se han finalizado. Hemos decidido tener varios tableros para el desarrollo del proyecto.
** Tablero general: que es donde hemos colocado los issues de la documentación, y donde colocaremos los issues que correspondan con tareas generales del proyecto.
** Tablero frontEnd: donde colocaremos todos los issues relacionados con la parte de desarrollo del frontEnd.
** Tablero backEnd: donde colocaremos todos los issues relacionados con la parte de desarrollo del backEnd
** Tablero base de datos: donde colocaremos todos los issues relacionados con la creación y gestión de la base de datos.
****
